### PR TITLE
Move to modern fsdocs tool

### LINKED ISSUE #16: Generating Documentation
### Description

I cannot find documentation on the library, nor is there any documentation on how to generate the documentation.

### Repro steps

1. The API Reference link is broken.  It produces an empty page.  http://fsprojects.github.io/ExcelFinancialFunctions/reference/index.html

2. The "/docs/content" folder has some text files that say there is a way to generate documentation but no instructions on how to do so.

### Expected behavior

I would expect a way to generate / view documentation

### Actual behavior

Current links are broken, not instrucitons on generating docs.

### Related information 

* Operating system: Windows 7
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: All
* Performance information, links to performance testing scripts: N/A

### PR DESCRIPTION
**Pull request by nhirschey**
Hi @jcoliz, thanks for updating this to netstandard2.0! I was watching this because I wanted to use it this spring on net6.0.

This pull request is all about updating the documentation tool and facilitating automatic docs deployment via github actions. the changes were:

0. Move release notes out of docs folder so that it doesn't get turned into a page on the docs website. If you wanted it on the docs website, sorry! it could be moved back.
1. update to use new fsdocs tool.
2. split into a two workflows so that docs are only deployed on pushes to the master (for example, like what Don Syme and Phillip Carter use on [FSharp.Data](https://github.com/fsprojects/FSharp.Data/tree/main/.github/workflows)).
3. Given that the old library had a githup pages set up, my guess is that on merging this PR to master this will redeploy the documentation site that is currently showing 404.

To see docs locally, do

```
dotnet tool restore
dotnet build --configuration=Release
dotnet fsdocs watch 
```

Closes #16

### CODE REVIEW

**Comment by jcoliz** [comment]
That's fantastic, thanks @nhirschey. Good thing, because I have no idea how the doc build system worked. I will spend some time with the PR to understand it all.

**Comment by jcoliz** [comment]
Awesome, thanks again for this Nicholas. It will be great to have a working docs page. I've run it, and I have a few questions to ask...

* The push-master.yml action makes use of the "GITHUB_TOKEN" secret. I do not see any secrets available in this repository. Will the action work in current form? If so, where does it get "GITHUB_TOKEN" from?
* The API reference seems to only show reference for publicenums.fs. However, the majority of functionality that's interesting to users is in wrapperdotnettype.fs. Do you know how we get items in that file to show up in the docs? There are "///" docs in that file, so I'd expect them.
* The sidebar links to License give a 404 error. It's looking for LICENSE.md, but the repo has LICENSE.txt. I'm not opposed to moving to a LICENSE.md if you wanted to replace it.

**Comment by sergey-tihon** [comment]
[GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) just available for you automatically inside GitHub Actions.

**Comment by nhirschey** [comment]
1. See Sergey's above comment about the github token.
2. Fixed the license path in latest commit.
3. The docs from wrapperdotnettype.fs are in the `Excel.FinancialFunctions.Financial` type.

image

**Comment by jcoliz** [comment]
Ok, thanks for the above. @sergey-tihon, appreciate the education on github token. I will have to think some more about the namespaces here, because having the many API at the same level as a random enum seems subpar for discoverability. Also, do you know how we can fix the [learn more] links in the screenshot above? It would seem that the intent is for them to be clickable links in the docs.

Anyway, nice work. Merging now. Also fixes #47

**Comment by nhirschey** [comment]
You could fix the [learn more] links by adding <UsesMarkdownComments> to the project file. See [here](https://fsprojects.github.io/FSharp.Formatting/apidocs.html). But the links in visual studio tooltips still won’t be [fixed](https://github.com/fsharp/fslang-suggestions/issues/237). 

It would probably be better to convert them to the standard XML href links described in fsharp formatting api docs so that it works on the web and in tooltips.

**Pull request merged**
