### PR TITLE
Build library as .NET Standard 2.1, tests as .NET Core 3.1 and NUnit 3

### PR DESCRIPTION
**Pull request by jcoliz**
Hi, I converted the library and NUnit tests to .NET Core, please have a look. I'm building these using Azure Pipelines at https://jcoliz.visualstudio.com/ExcelFinancialFunctions/_build. The only real change I had to make is that the tests would not discover without the change to parseArray. 

Haven't touched the Excel tests yet.

(Related to Issue #9)

### CODE REVIEW

**Comment by jcoliz** [comment]
Yah, I'm happy to help. This PR has literally the first line of F# I've ever written, but I do know .NET and Excel.

**Comment by dsyme** [comment]
@jcoliz Nice work! :)

I'll make you co-admin

**Comment by dsyme** [comment]
@jcoliz Any chance you could move CI to Github actions?  That's what most of the projects in "fsprojects" use

**Comment by jcoliz** [comment]
Right, I'm happy to take a TODO on that. I used Azure Pipelines because it's what I know. I've been meaning to figure out Github actions.

**Comment by dsyme** [comment]
Cool thanks :)

**Pull request merged**
