### PR TITLE
Added strong name signing

### PR DESCRIPTION
**Pull request by derekdiamond**

### CODE REVIEW

**Comment by jcoliz** [comment]
Hi, @derekdiamond. Thanks for contributing this. Could you please describe the case where you are finding it necessary or useful to have this library strong-named?

Thanks!

**Comment by derekdiamond** [comment]
Hi @jcoliz 
A pleasure. I have strong named assemblies that reference ExcelFinancialFunctions, and the compile fails because strong named assemblies are not allowed to reference non strong names assemblies. It is irritating, but I need my assemblies to be strong named in case they are referenced by strong named assemblies!

**Comment by jcoliz** [comment]
Ok, thanks, @derekdiamond . I will look into this. Another one of my repos is asking for it too, I will try it out there first, to avoid breaking anything here.

Also, I noticed you changed

```
 <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
```

It this required for strong naming?

**Comment by jcoliz** [comment]
Hi, @derekdiamond . I've merged this, and release an RC package. It would be great if you could try it out, then report back that this meets your needs. Thanks!

https://www.nuget.org/packages/ExcelFinancialFunctions/3.3.0-rc1

**Pull request merged**
