### PR TITLE
fix yield for the last period before maturity

### PR DESCRIPTION
**Pull request by cpell**
This fix works. Could it be merged into the master branch?

### CODE REVIEW

**Comment by luajalla** [comment]
Thank you! I couldn't test it propertly without Excel... nice to know it works.

**Comment by cpell** [comment]
Ah, I see. I tried to test it previously but didn't realize it wasn't in the master branch so the builds I was testing did not actually have the fix. Thanks!

**Comment by dsyme** [comment]
Hi @cpell - I was chatting with @luajalla and we wondered if you would like to be a co-maintainer on this repo?  That would allow you to post updated Nuget packages as well.  Please let us know what you think.  We'd write up some dev notes on updating the packages

Cheers!
don

**Comment by cpell** [comment]
Hi @dsyme,
Thanks for reaching out. I'm happy to help where I can with maintaining the repo.
Chris

**Comment by luajalla** [comment]
Hi @cpell, do you have a nuget account? if so, what is your user name there?

Thanks,
Natallie

**Comment by cpell** [comment]
@luajalla Accepted invite and created nuget account as cpell.

**Comment by luajalla** [comment]
Thanks, done!

**Pull request merged**
